PAIS/Models/ViewModels/EditUserViewModel.cs
namespace PAIS.Models.ViewModels
{
    public class EditUserViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string LoginName { get; set; }
    }
}

PAIS/Controllers/ShopAdminController.cs
using Microsoft.AspNetCore.Mvc;
using PAIS.Models;
using PAIS.Models.ViewModels;
using System.Linq;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace PAIS.Controllers
{
    [Authorize(Roles = "shop admin")]
    public class ShopAdminController : Controller
    {
        private IBookRepository bookRepository;
        private ICommentRepository commentRepository;
        private IRateRepository rateRepository;

        public ShopAdminController(IBookRepository bRepo, ICommentRepository cRepo, IRateRepository rRepo)
        {
            bookRepository = bRepo;
            commentRepository = cRepo;
            rateRepository = rRepo;
        }

        public ViewResult Index(string search = "") => View(bookRepository.Books.Where(b => b.Name.Contains(search)));

        public ViewResult Edit(int bookId)
        {
            Book model = bookRepository.GetBook(bookId);

            return View(new BookViewModel
            {
                BookID = model.BookID,
                Name = model.Name,
                Description = model.Description,
                Author = model.Author,
                Format = model.Format,
                PublicationDate = model.PublicationDate,
                PublicationType = model.PublicationType,
                Binder = model.Binder,
                Amount = model.Amount,
                Anotation = model.Anotation,
                ISBNCode = model.ISBNCode,
                Price = model.Price,
                Rate = model.Rate,
                RatesAmount = model.RatesAmount
            });
        }

        [HttpPost]
        public IActionResult Edit(BookViewModel model)
        {
            if (ModelState.IsValid)
            {
                Book newBook = new Book
                {
                    BookID = model.BookID,
                    Name = model.Name,
                    Description = model.Description,
                    Author = model.Author,
                    Format = model.Format,
                    PublicationDate = model.PublicationDate,
                    PublicationType = model.PublicationType,
                    Binder = model.Binder,
                    Amount = model.Amount,
                    Anotation = model.Anotation,
                    ISBNCode = model.ISBNCode,
                    Price = model.Price,
                    Rate = model.Rate,
                    RatesAmount = model.RatesAmount
                };
                if (model.Image != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(model.Image.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)model.Image.Length);
                    }
                    newBook.Image = imageData;
                }
                else
                {
                    return RedirectToAction("Error");
                }

                bookRepository.SaveBook(newBook);
                TempData["message"] = $"{newBook.Name} була збережена";
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(model);
            }
        }

        public ViewResult Create() => View("Edit", new BookViewModel() { Rate = 0, RatesAmount = 0 });

        [HttpPost]
        public IActionResult Delete(int bookId)
        {
            Book deletetBook = bookRepository.DeleteBook(bookId);

            commentRepository.DeleteBookComments(bookId);
            rateRepository.DeleteBookRates(bookId);

            if (deletetBook != null)
            {
                TempData["message"] = $"{deletetBook.Name} була видалена";
            }

            return RedirectToAction("Index");
        }
    }
}

PAIS/Views/ShopAdmin/Edit.cshtml
@model BookViewModel

@{
    ViewData["Title"] = "Редагування книги";
    Layout = "_Layout";
}

    <h2>
        Редагування книги
    </h2>

<hr />

    <form asp-action="Edit" style="padding:0px;" method="post" class="col-md-6 col-lg-5" enctype="multipart/form-data">
        <input type="hidden" asp-for="BookID" />
        <div class="form-group">
            <label asp-for="Name">Назва книги</label>
            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <input asp-for="Name" class="form-control" />
        </div>
       <div>
            <label asp-for="Image">Зображення</label>
            <div><span asp-validation-for="Image" class="text-danger"></span></div>
            <input type="file" asp-for="Image" class="form-control-file border" required/>
        </div>
        <div class="form-group">
            <label asp-for="Description">Опис</label>
            <div><span asp-validation-for="Description" class="text-danger"></span></div>
            <input asp-for="Description" class="form-control"/>
        </div>
        <div class="form-group">
            <label asp-for="Author">Автор</label>
            <div><span asp-validation-for="Author" class="text-danger"></span></div>
            <input asp-for="Author" class="form-control"/>
        </div>
        <div class="form-group">
            <label asp-for="Format">Формат</label>
            <div><span asp-validation-for="Format" class="text-danger"></span></div>
            <input asp-for="Format" class="form-control"/>
        </div>
        <div class="form-group">
            <label asp-for="PublicationDate">Дата публікації</label>
            <div><span asp-validation-for="PublicationDate" class="text-danger"></span></div>
            <input asp-for="PublicationDate" type="number" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="PublicationType">Тип видання</label>
            <div><span asp-validation-for="PublicationType" class="text-danger"></span></div>
            <input asp-for="PublicationType" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Binder">Палітурка</label>
            <div><span asp-validation-for="Binder" class="text-danger"></span></div>
            <input asp-for="Binder" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Amount">Обсяг</label>
            <div><span asp-validation-for="Amount" class="text-danger"></span></div>
            <input asp-for="Amount" type="number" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Anotation">Анотація</label>
            <div><span asp-validation-for="Anotation" class="text-danger"></span></div>
            <textarea asp-for="Anotation" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="ISBNCode"></label>
            <div><span asp-validation-for="ISBNCode" class="text-danger"></span></div>
            <input asp-for="ISBNCode" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price">Ціна</label>
            <div><span asp-validation-for="Price" class="text-danger"></span></div>
            <input asp-for="Price" class="form-control" />
        </div>

        <div>
            <button class="btn btn-outline-dark" type="submit">Зберегти</button>
            <a asp-action="Index" class="btn btn-link">Відмінити</a>
        </div>
    </form>
<hr />

PAIS/Views/ShopAdmin/EditUser.cshtml
@model EditUserViewModel
@{
    ViewData["Title"] = "Edit user";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row ">
    <div class="col-md-12">
        <form asp-action="EditUser" asp-controller="ManageUsers">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
            </div>
            <div class="form-group">
                <label class="control-label">Email</label>
                <input type="text" asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Логін</label>
                <input type="text" asp-for="LoginName" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

PAIS/Views/ShopAdmin/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "Всі книги";
    Layout = "_Layout";
}

<h2 class="p-1">Всі книги</h2>
@(await Html.PartialAsync("StatusMessage", TempData["message"]))
<hr />
<div class="d-flex justify-content-center">
    <div class="col-8 mt-3">
        <form asp-action="Index" asp-controller="ShopAdmin" method="get">
            <div class="row">
                <div class="col-11 p-0">
                    <input type="text" class="form-control border-primary w-100 my-0" placeholder="Пошук книги" name="search">
                </div>
                <div class="col-1 p-0">
                    <button type="submit" class="btn btn-primary my-0"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="p-1" style="margin-bottom:5px;">
    <a asp-action="Create" style="text-decoration: none;" class="btn btn-sm btn-link">Добавити книгу</a>
</div>

<table class="table table-sm">
    <tr>
        <th>Назва</th>
        <th>Тип видання</th>
        <th class="text-right">Ціна</th>
        <th class="text-center">Дії</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.PublicationType</td>
            <td class="text-right">@item.Price.ToString("c")</td>
            <td class="text-center">
                <form asp-action="Delete" method="post">
                    <a style="text-decoration: none;" asp-action="Edit" class="btn btn-sm btn-link"
                       asp-route-bookId="@item.BookID">
                        Редагувати
                    </a>
                    |
                    <input type="hidden" name="BookID" value="@item.BookID" />
                    <button style="text-decoration: none;" type="submit" class="btn btn-sm btn-link">
                        Видалити
                    </button>
                </form>
            </td>
        </tr>
    }
</table>