PAIS/Models/Data/FeedBack.cs
namespace PAIS.Models
{
    public class FeedBack
    {
        public string Name { get; set; }
        public string Mail { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}

PAIS/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PAIS.Models;

namespace PAIS.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

PAIS/Controllers/UsersAdminController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using PAIS.Models;
using PAIS.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PAIS.Controllers
{
    [Authorize(Roles = "user admin")]
    public class UsersAdminController : Controller
    {
        private UserManager<IdentityUser> userManager;
        private RoleManager<IdentityRole> roleManager;
        private IRateRepository rateRepository;
        private ICommentRepository commentRepository;
        private IBlockedUserRepository blockedUserRepository;

        public UsersAdminController(RoleManager<IdentityRole> _roleManager, UserManager<IdentityUser> _userManager,
            ICommentRepository _commentRepository, IBlockedUserRepository _blockedUserRepository, 
            IRateRepository _rateRepository)
        {
            userManager = _userManager;
            roleManager = _roleManager;
            rateRepository = _rateRepository;
            commentRepository = _commentRepository;
            blockedUserRepository = _blockedUserRepository;
        }

        [HttpGet]
        public IActionResult Index(string search = "")
        {
            List<IdentityUser> Users = new List<IdentityUser>();
            Users = userManager.Users.ToList();

            return View(Users.Where(u => u.UserName.Contains(search)));
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            IdentityUser user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Error");
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, LoginName = user.UserName };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.UserName = model.LoginName;

                    var result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        TempData["message"] = $"{user.UserName} був змінений";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteUser(string id)
        {
            IdentityUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    return RedirectToAction("Error");
                }
            }
            commentRepository.DeleteUserComments(id);
            rateRepository.DeleteUserRates(id);

            TempData["message"] = $"Користувач {user.UserName} видалений";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditUserRoles(string userId)
        {
            // get user
            IdentityUser user = await userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // gets user`s roles list
                var userRoles = await userManager.GetRolesAsync(user);
                var allRoles = roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return RedirectToAction("Error");
        }

        [HttpPost]
        public async Task<IActionResult> EditUserRoles(string userId, List<string> roles)
        {
            // gets user
            IdentityUser user = await userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // gets user`s roles list
                var userRoles = await userManager.GetRolesAsync(user);
                // gets all roles
                var allRoles = roleManager.Roles.ToList();
                // gets roles list, that was added 
                var addedRoles = roles.Except(userRoles);
                // gets roles that was deleted
                var removedRoles = userRoles.Except(roles);

                await userManager.AddToRolesAsync(user, addedRoles);

                await userManager.RemoveFromRolesAsync(user, removedRoles);

                TempData["message"] = $"Роль користувача {user.UserName} була змінена";
                return RedirectToAction("Index");
            }

            return RedirectToAction("Error");
        }

        [HttpGet]
        public IActionResult BlockUser(string UserId, string BookId)
        {
            // block user
            BlockedUser blockedUser = new BlockedUser { UserId = UserId };
            blockedUserRepository.SaveBlockedUser(blockedUser);

            // delete all his comments
            commentRepository.DeleteUserComments(UserId);

            return RedirectToAction("Details", "Home", new { bookId = BookId });
        }

        [HttpGet]
        public IActionResult UnblockUser(string UserId)
        {
            if (string.IsNullOrEmpty(UserId))
            {
                RedirectToAction("Error");
            }
            string id = blockedUserRepository.BlockedUsers.First(u => u.UserId == UserId).UserId;
            blockedUserRepository.DeleteBlockedUser(id);

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new  { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PAIS/Views/Shared/AddCommentPartial.cshtml
@inject SignInManager<IdentityUser> signInManager
@inject UserManager<IdentityUser> userManager
@inject IBlockedUserRepository blockedUserRepository

@model Comment
<h3 class="mt-5">Добавити коментар</h3>
@{bool isBlocked = false;}
@if (signInManager.IsSignedIn(User))
{
    isBlocked = blockedUserRepository.BlockedUsers.Where(b => b.UserId == userManager.GetUserId(User)).Any();
    if (!isBlocked)
    {
        <form asp-action="AddComment" asp-controller="Home" method="post">
            <div class="form-group">
                <input type="hidden" asp-for="OwnerId" value="@((await userManager.GetUserAsync(User)).Id)" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="BookId" value="@Model.BookId" />
            </div>
            <div class="form-group">
                <textarea class="form-control" asp-for="Text" required rows="3"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Коментувати" class="btn btn-success" />
            </div>
        </form>
    }
    else
    {
        <h4 style="color:brown">Ви не можете залишити коментар, тому що ви заблоковані!</h4>
    }
}

else
{
    <h4 style="color:brown">Авторизуйтесь або зареєструйтесь, для того щоб залишити коментар!</h4>
    <form asp-action="AddComment" asp-controller="Home" method="post">
        <div class="form-group">
            <textarea class="form-control" disabled rows="3"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="Comment" class="btn btn-success" />
        </div>
    </form>
}

PAIS/Views/Shared/AllCommentPartial.cshtml
@model IEnumerable<Comment>

<hr style="border-width: 2px; border-color: grey;" />
<h3>@Model.Count() коментарів</h3>
<hr style="border-width: 2px; border-color: grey;" />
@foreach (var c in Model.OrderByDescending(c => c.Time))
{
    @await Html.PartialAsync("CommentPartial", c)
    <hr style="border-width: 2px; border-color: grey;" />
}

PAIS/Views/Shared/BookPartial.cshtml
@model Book
<div class="row">
    <div class="col-lg-3 d-flex flex-column">
        <img class="mx-auto p-2" style="width:200px; height:280px;" alt="@Model.Name" src="data:image/jpeg;base64,@(Convert.ToBase64String(@Model.Image))" />
    </div>
    <div class="col-lg-9 p-3">
        <div class="">
            <h4>
                @Model.Name

                <span class="badge badge-pill badge-primary col-2 p-2" style="float:right">
                    @Model.Price.ToString("c")
                </span>
            </h4>
        </div>
        <div class="card-text p-1"><h5>@Model.Description</h5></div>
        <p>
            Автор: @Model.Author<br />
            Формат: @Model.Format<br />
            Дата публікації: @Model.PublicationDate<br />
            Тип видання: @Model.PublicationType<br />
            Палітурка: @Model.Binder<br />
            Обсяг: @Model.Amount с.
        </p>
    </div>
</div>
<div class="">
    <p>Анотація: @Model.Anotation</p>
    <p>ISBNCode: @Model.ISBNCode</p>
</div>
<form id="@Model.BookID" asp-action="AddToCart"
      asp-controller="Cart" method="post" class="m-2">
    <input type="hidden" asp-for="BookID" />
    <input type="hidden" name="returnUrl"
           value="@ViewContext.HttpContext.Request.PathAndQuery()" />
    <span class="card-text p-1">
        <button type="submit"
                class="btn btn-success pull-right" style="float:right">
            В корзину
        </button>
    </span>
</form>

PAIS/Views/Shared/BookSummary.cshtml
@model Book

<div class="card border-0 card-outline-primary m-1 p-2">
    <div class="d-flex flex-column">
        <img class="mx-auto p-2" style="width:200px; height:280px;" alt="@Model.Name" src="data:image/jpeg;base64,@(Convert.ToBase64String(@Model.Image))" />
    </div>
    <div class="bg-faded" style="height:70px;">
        <p class="text-center">
            <a class="text-decoration-none" asp-controller="Home" asp-action="Details" asp-route-bookId="@Model.BookID">@Model.Name</a>
        </p>
    </div>
    
    <p class="text-center">Рік: @Model.PublicationDate | Оцінка: @Model.Rate</p>
    <div class="row pl-4">
        <span class="badge badge-success p-2 col-4 pull-left">
            @Model.Price.ToString("c")
        </span>
        <form class="col-8 pr-4" id="@Model.BookID" asp-action="AddToCart"
              asp-controller="Cart" method="post">
            <input type="hidden" asp-for="BookID" />
            <input type="hidden" name="returnUrl"
                   value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text p-1">
                <button type="submit"
                        class="btn btn-success btn-sm pull-right">
                    В корзину
                </button>
            </span>
        </form>
    </div>
</div>

PAIS/Views/Shared/CommentPartial.cshtml
@inject ICommentRepository commentRepository
@inject UserManager<IdentityUser> userManager
@inject SignInManager<IdentityUser> signInManager

@model Comment

    <div class="row p-1">
        @if ((signInManager.IsSignedIn(User)) && ((await userManager.GetUserAsync(User)).Id == Model.OwnerId))
        {
            <div class="col-lg-12 row m-0">
                <p class="m-0 p-0 col-lg-12">
                    <b><ins style="color:dodgerblue">You</ins></b>  <em style="color:dimgrey">@Model.Time</em>
                </p>

                <div class="col-lg-10 p-0">
                    <form asp-action="EditComment" asp-controller="Home" method="post">
                        <div class="form-group">
                            <input type="hidden" asp-for="CommentId" value="@Model.CommentId" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" asp-for="OwnerId" value="@((await userManager.GetUserAsync(User)).Id)" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" asp-for="BookId" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" asp-for="Time" value="@Model.Time" />
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="text">@Model.Text</textarea>
                        </div>
                        <div class="form-group m-0">
                            <input type="submit" value="Edit" class="btn btn-success" />
                        </div>
                    </form>
                </div>
                <div class="col-lg-2">
                    <form asp-action="DeleteComment" asp-controller="Home" method="post">
                        <div class="form-group">
                            <input type="hidden" asp-for="CommentId" value="@Model.CommentId" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" asp-for="BookId" value="@Model.BookId" />
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-danger" value="Видалити" />
                        </div>
                    </form>
                </div>
            </div>
        }
        else if ((signInManager.IsSignedIn(User)) &&
            (await userManager.IsInRoleAsync((await userManager.GetUserAsync(User)), "user admin")) &&
            !(await userManager.IsInRoleAsync((await userManager.GetUserAsync(User)), "shop admin")))
        {

            @if ((await userManager.IsInRoleAsync((userManager.Users.First(u => u.Id == Model.OwnerId)), "user admin")) &&
                (await userManager.IsInRoleAsync((userManager.Users.First(u => u.Id == Model.OwnerId)), "shop admin")))
            {
                <div class="col-lg-11">
                    <p><ins style="color:black">@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins>  <em style="color:dimgrey">@Model.Time</em></p>
                    <p class="h5 text-secondary border px-3 py-2 rounded">@Model.Text</p>
                </div>
            }   
            else if ((await userManager.IsInRoleAsync((userManager.Users.First(u => u.Id == Model.OwnerId)), "user admin")))
            {
                <div class="col-lg-11">
                    <p style="color:firebrick">
                        <ins style="color:black">@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins> User admin  <em style="color:dimgrey">@Model.Time</em>
                    </p>
                    <div class="form-group">
                        <p class="h5 text-secondary border px-3 py-2 rounded">@Model.Text</p>
                    </div>
                </div>
            }
            else
            {
                <div class="col-lg-12">
                    @if ((await userManager.IsInRoleAsync((userManager.Users.First(u => u.Id == Model.OwnerId)), "shop admin")))
                    {
                        <p style="color: seagreen">
                            <ins style="color:black">@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins> Shop admin <em style="color:dimgrey">@Model.Time</em>
                        </p>

                    }
                    else
                    {
                        <p style="color:dimgrey"><ins>@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins> <em>@Model.Time</em></p>
                    }
                    <div class="col-lg-10">
                        <p class="h5 text-secondary border px-3 py-2 rounded">@Model.Text</p>
                    </div>
                    <div class="col-lg-2">
                        <form asp-action="DeleteComment" asp-controller="Home" method="post">
                            <div class="form-group">
                                <input type="hidden" asp-for="CommentId" value="@Model.CommentId" />
                            </div>
                            <div class="form-group">
                                <input type="hidden" asp-for="BookId" value="@Model.BookId" />
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-danger" value="Видалити" />
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-2">
                        <a class="btn btn-sm btn-warning" asp-action="BlockUser" asp-controller="UsersAdmin" asp-route-UserId="@Model.OwnerId" asp-route-BookId="@Model.BookId">Заблокув.</a>
                    </div>
                </div>
            }
        }
        else if ((signInManager.IsSignedIn(User)) &&
        (await userManager.IsInRoleAsync((await userManager.GetUserAsync(User)), "user admin")) &&
        (await userManager.IsInRoleAsync((await userManager.GetUserAsync(User)), "shop admin")))
        {

    <div class="col-lg-12 row m-0">
        
        <div class="col-lg-12 p-0">
            @if ((await userManager.IsInRoleAsync((userManager.Users.First(u => u.Id == Model.OwnerId)), "user admin")))
            {
                <p style="color: firebrick">
                    <ins style="color:black">@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins> User admin <em style="color:dimgrey">@Model.Time</em>
                </p>
            }
            else if ((await userManager.IsInRoleAsync((userManager.Users.First(u => u.Id == Model.OwnerId)), "shop admin")))
            {
                <p style="color: seagreen">
                    <ins style="color:black">@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins> Shop admin <em style="color:dimgrey">@Model.Time</em>
                </p>
            }
            else
            {
                <p style="color:dimgrey"><ins>@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins> <em>@Model.Time</em></p>
            }
        </div>
        <div class="col-lg-10 p-0">
            <p class="h5 text-secondary border px-3 py-2 rounded">@Model.Text</p>
        </div>
        <div class="col-lg-2">
            <form asp-action="DeleteComment" style="margin-top: 0px;" asp-controller="Home" method="post">
                <div class="form-group">
                    <input type="hidden" asp-for="CommentId" value="@Model.CommentId" />
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="BookId" value="@Model.BookId" />
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-danger" value="Видалити" />
                </div>
            </form>
        </div>
        <a class="btn btn-warning" asp-action="BlockUser" asp-controller="UsersAdmin" asp-route-UserId="@Model.OwnerId" asp-route-BookId="@Model.BookId">Заблокувати</a>
    </div>

        }
        else
        {
            @if ((await userManager.IsInRoleAsync((userManager.Users.First(u => u.Id == Model.OwnerId)), "user admin")) ||
         (await userManager.IsInRoleAsync((userManager.Users.First(u => u.Id == Model.OwnerId)), "shop admin")))
            {
                <div class="col-lg-12">
                    <p style="color: red"><ins style="color:black">@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins> Адміністратор <em style="color:dimgrey">@Model.Time</em></p>
                </div>
            }
            else
            {
                <div class="col-lg-12">
                    <p style="color:dimgrey"><ins>@((userManager.Users.First(u => u.Id == Model.OwnerId)).UserName)</ins> <em>@Model.Time</em></p>
                </div>
            }
            <div class="col-lg-12">
                <p class="h5 text-secondary border px-3 py-2 rounded">@Model.Text</p>
            </div>
        }

    </div>

PAIS/Views/Shared/FeedBack.cshtml
@model FeedBack

<form asp-controller="Home" asp-action="SendMessage" method="post">
    <div>
        <div class="form-group">
            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <input asp-for="Name" type="text" class="form-control" placeholder="Ім'я" required>
        </div>
        <div class="form-group">
            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <input asp-for="Mail" type="email" class="form-control" placeholder="Email" required>
        </div>
        <div class="form-group">
            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <input asp-for="Subject" type="text" class="form-control" placeholder="Тема" required>
        </div>
        <textarea asp-for="Message" class="form-control" placeholder="Повідомлення" required></textarea>
        <button type="submit" class=" pull-right btn btn-success btn-sm mt-2">Надіслати</button>
    </div>
</form>

PAIS/Views/Shared/LoginPartial.cshtml
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{ 
    <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" style="color: white" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@UserManager.GetUserName(User)</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
            <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Профіль" class="dropdown-item btn-link">Профіль</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/Identity/Account/Manage/ChangePassword" title="Books">Змінити пароль</a>
            <a class="dropdown-item" href="/Identity/Account/Manage/PersonalData" title="Books">Особисті дані</a>
            @if (await UserManager.IsInRoleAsync((await UserManager.GetUserAsync(User)), "user admin"))
            {
                <a class="dropdown-item" href="/UsersAdmin/Index" title="Users">Користувачі <span style="color:orangered;">(А)</span></a>
            }
            @if (await UserManager.IsInRoleAsync((await UserManager.GetUserAsync(User)), "shop admin"))
            {
                <a class="dropdown-item" href="/Order/List" title="Orders">Замовлення <span style="color:orangered;">(А)</span></a>
                <a class="dropdown-item" href="/NewsAdmin/Index" title="News">Новини <span style="color:orangered;">(А)</span></a>
                <a class="dropdown-item" href="/ShopAdmin/Index" title="Books">Товари <span style="color:orangered;">(А)</span></a>
            }
        </div>
    </div>
    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("List", "Home", new { area = "" })" method="post" id="logoutForm">

        <button type="submit" class="btn-danger btn-sm btn m-1">Вийти</button>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right flex-md-row">
        <li class="nav-item pl-md-3"><a asp-area="Identity" asp-page="/Account/Register" class="nav-link">Реєстрація</a></li>
        <li class="nav-item pl-md-3"><a asp-area="Identity" asp-page="/Account/Login" class="nav-link">Вхід</a></li>
    </ul>
}

PAIS/Views/Shared/NewsSummary.cshtml
@model News

<div class="card card-outline-primary p-2 mb-2 col-lg-12">
        <div>
            <h3><a class="text-decoration-none" asp-controller="Home" asp-action="NewsDetails" asp-route-newsID="@Model.NewsID">@Model.Name</a></h3>
            <p>@Model.Date.ToString("MM/dd/yyyy") @Model.Author</p>
        </div>

        <div class="card-text p-1">
            @if (Model.Description.Length > 372)
            {
                @Model.Description.Substring(0, Math.Min(Model.Description.Length, 372));@:...
            }
            else
            {
                @Model.Description;
            }
        </div>

        <div>
            <a asp-action="NewsDetails" asp-controller="Home" asp-route-newsID="@Model.NewsID" >
                <span class="btn btn-outline-primary pull-right">Читати далі</span>
            </a>
        </div>
    </div>

PAIS/Views/Shared/RatePartial.cshtml
@model Rate

<form asp-action="RateBook" asp-controller="Home" method="post" class="d-flex">
    <div class="form-group">
        <input type="hidden" asp-for="@Model.UserId" />
    </div>

    <div class="form-group">
        <input type="hidden" asp-for="@Model.BookId" />
    </div>

    <div class="form-group pt-3">
        <select type="number" asp-for="@Model.Value" class="form-control rate-select">
            @for (int i = 1; i <= 5; i++)
            {
                <option value="@i">@i</option>
            }
        </select>
    </div>
    <div class="form-group mb-2 d-flex align-items-center ml-3">
        <input type="submit" value="Оцінити" class="btn btn-sm btn-success" />
    </div>
</form>

PAIS/Views/Shared/StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Закрити"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

PAIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.min.css">
    <script src="~/lib/jquery/dist/jquery.slim.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="container">
            <a class="navbar-brand" asp-action="List" asp-controller="Home">ПАІС</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar1">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-action="About" asp-controller="Home">Про нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="List" asp-controller="Home" asp-route-type="">Видання</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="NewsList" asp-controller="Home">Новини</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Contacts" asp-controller="Home">Контакти</a>
                    </li>
                </ul>

                <div>
                    @await Component.InvokeAsync("CartSummary")
                </div>

                <form asp-controller="Home" asp-action="List" method="get" class="form-inline my-2 my-lg-0" style="margin-right:4px; margin-left:4px;">
                    <input class="form-control form-control-sm mr-sm-1" type="text"
                           name="search" placeholder="Пошук" aria-label="Search">
                </form>

                @await Html.PartialAsync("LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container" style="margin-top: 20px; margin-bottom:50px;">
        @RenderBody()
    </div>
    <div class="navbar navbar-dark bg-dark" style="position:fixed; height:40px; bottom:0px; right: 0px; left:0px;">
        <div class="container text-white">
            <div>
                © 2019 Copyright:
                <a href="#" style="color: lightgrey;">Markiyan Haihel</a>
            </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>