PAIS/Controllers/NewsAdminController.cs
using Microsoft.AspNetCore.Mvc;
using PAIS.Models;
using PAIS.Models.ViewModels;
using System.Linq;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace PAIS.Controllers
{
    [Authorize(Roles = "shop admin")]
    public class NewsAdminController : Controller
    {
        private INewsRepository repository;

        public NewsAdminController(INewsRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(string search = "") => View(repository.NewsRepo.Where(n => n.Name.Contains(search)));

        public ViewResult Edit(int newsID)
        {
            News model = repository.NewsRepo
                   .FirstOrDefault(b => b.NewsID == newsID);

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(News model)
        {
            if (ModelState.IsValid)
            {
                repository.SaveNews(model);
                TempData["message"] = $"Новину: {model.Name} було збережено";
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(model);
            }
        }

        public ViewResult Create() => View("Edit", new News() { Date = DateTime.Now });

        [HttpPost]
        public IActionResult Delete(int newsID)
        {
            News deletedNews = repository.DeleteNews(newsID);

            if (deletedNews != null)
            {
                TempData["message"] = $"Новину: {deletedNews.Name} було видалено";
            }

            return RedirectToAction("Index");
        }
    }
}

PAIS/Views/NewsAdmin/Edit.cshtml
@model News

@{
    ViewData["Title"] = "Редагування новини";
    Layout = "_Layout";
}

<h2>
    Редагування новини
</h2>

<hr />

<form asp-action="Edit" style="padding:0px;" method="post" class="col-md-6 col-lg-5">
    <input type="hidden" asp-for="NewsID" />
    <div class="form-group">
        <label asp-for="Name">Назва</label>
        <div><span asp-validation-for="Name" class="text-danger"></span></div>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description">Опис</label>
        <div><span asp-validation-for="Description" class="text-danger"></span></div>
        <textarea asp-for="Description" class="form-control" rows="5"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="Author">Автор</label>
        <div><span asp-validation-for="Author" class="text-danger"></span></div>
        <input asp-for="Author" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Date">Дата</label>
        <div><span asp-validation-for="Date" class="text-danger"></span></div>
        <input type="date" asp-for="Date" class="form-control " />
    </div>
    <div class="text-center">
        <button class="btn btn-outline-dark" type="submit">Зберегти</button>
        <a asp-action="Index" class="btn btn-link">Відмінити</a>
    </div>
</form>
<hr />

PAIS/Views/NewsAdmin/Index.cshtml
@model IEnumerable<News>

@{
    ViewData["Title"] = "Всі новини";
    Layout = "_Layout";
}

<h2 class="p-1">Всі новини</h2>
@(await Html.PartialAsync("StatusMessage", TempData["message"]))
<div class="d-flex justify-content-center">
    <div class="col-8 mt-3">
        <form asp-action="Index" asp-controller="NewsAdmin" method="get">
            <div class="row">
                <div class="col-11 p-0">
                    <input type="text" class="form-control border-primary w-100 my-0" placeholder="Пошук новини" name="search">
                </div>
                <div class="col-1 p-0">
                    <button type="submit" class="btn btn-primary my-0"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="p-1" style="margin-bottom:5px;">
    <a asp-action="Create" style="text-decoration: none;" class="btn btn-sm btn-link">Добавити новину</a>
</div>

<table class="table table-sm">
    <tr>
        <th>Назва</th>
        <th class="text-right">Дата</th>
        <th class="text-right">Автор</th>
        <th class="text-center">Дії</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td class="text-right">@item.Date.ToString("MM/dd/yyyy")</td>
            <td class="text-right">@item.Author</td>
            <td class="text-center">
                <form asp-action="Delete" method="post">
                    <a style="text-decoration: none;" asp-action="Edit" class="btn btn-sm btn-link"
                       asp-route-newsId="@item.NewsID">
                        Редагувати
                    </a>
                    |
                    <input type="hidden" name="NewsID" value="@item.NewsID" />
                    <button style="text-decoration: none;" type="submit" class="btn btn-sm btn-link">
                        Видалити
                    </button>
                </form>
            </td>
        </tr>
    }
</table>